server_settings:
  port: 8080

scraping:
  interval: 10s
  timeout: 1s
  max_parallel: 10

documentation:
  title: "DR documentation"
  url: "https://google.com"

locations:
  - name: Hadera
    latitude: 32.446235
    longitude: 34.903852
  - name: Jerusalem
    latitude: 31.782904
    longitude: 35.214774
  - name: Beer Sheva
    latitude: 31.245381
    longitude: 34.788745
  - name: Netanya
    latitude: 33.04198
    longitude: 35.51537
  - name: negev
    latitude: 29.96649
    longitude: 34.89450

prometheus_servers:
  - name: prom1
    url: http://nginx:9090
  - name: prom2
    url: http://nginx:9090

applications:
  - name: app1
    location: Hadera
    metric: up{instance="app:8080", job="app"}
    prometheus: prom1
  - name: app3
    location: Jerusalem
    metric: up{instance="localhost:9090", job="prometheus"}
    prometheus: prom1
  - name: app4
    location: Beer Sheva
    metric: up{instance="app:8080", job="app"}
    prometheus: prom1
  - name: app2
    location: Hadera
    metric: up{instance="app:8080", job="app"}
    prometheus: prom2
  - name: app5
    location: Netanya
    metric: 1 - up{instance="localhost:9090", job="prometheus"}
    prometheus: prom1
  - name: app6
    location: Beer Sheva
    metric: up{instance="app:8080", job="app"}
    prometheus: prom1
  - name: app7
    location: Hadera
    metric: 1 - up{instance="localhost:9090", job="prometheus"}
    prometheus: prom2

sites:
  - name: "Test Site"
    url: "http://example.com"
    check_interval: "1m"
    timeout: "5s"
