server_settings:
  port: 8080
  sync_enable: true
  sync_port: 3030
  custom_ca_path: /etc/site-availability/certs/site-a-ca.crt

scraping:
  interval: "60s"
  timeout: "15s"
  max_parallel: 10

documentation:
  title: "Site B Documentation"
  url: "https://site-b.example.com/docs"

locations:
  - name: "site b"
    latitude: 31.782904
    longitude: 35.214774

prometheus_servers:
  - name: prom1
    url: http://prometheus:9090/

applications:
  - name: "app 2"
    location: "site b"
    metric: 'up{instance="app2"}'
    prometheus: "prom1"

sites:
  - name: "Site A"
    url: "https://site-availability-a:3030"
    enabled: true
    timeout: "5s"
    custom_ca_path: "/etc/site-availability/certs/site-a-ca.crt"
