services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: levytal/site-availability
    environment:
      - CONFIG_FILE=/app/config.yaml
      - CREDENTIALS_FILE=/app/credentials.yaml
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./credentials.yaml:/app/credentials.yaml
    ports:
      - "8080:8080"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    ports:
      - "9090:9090"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090"
