scrape_interval: 10s
locations:
- name: “Hadera”
  Latitude: 32.446235
  Longitude: 34.903852
- name: “Jerusalem”
  Latitude: 31.782904
  Longitude: 35.214774
- name: “Beer Sheva”
  Latitude: 31.245381
  Longitude: 34.788745
apps:
- name: app1
  location: Hadera
  metric: up{instance="app:8080", job="app"}
  prometheus: http://localhost:9090/
- name: app2
  location: Jerusalem
  metric: up{instance="app:8080", job="app"}
  prometheus: http://localhost:9090/
- name: app3
  location: Jerusalem
  metric: up{instance="localhost:9090", job="prometheus"}
  prometheus: http://localhost:9090/
- name: app4
  location: Beer Sheva
  metric: up{instance="app:8080", job="app"}
  prometheus: http://localhost:9090/