scrape_interval: 10s
locations:
#- name: Hadera
#  latitude: 32.446235
#  longitude: 34.903852
#- name: Jerusalem
#  latitude: 31.782904
#  longitude: 35.214774
#- name: Beer Sheva
#  latitude: 31.245381
#  longitude: 34.788745
- name: Yona
  latitude: 32.31443
  longitude: 34.92621
- name: Natanya
  latitude: 32.31746
  longitude: 34.86765
#- name: Los Angeles
#  latitude: 34.052235
#  longitude: -118.243683
#- name: Chicago
#  latitude: 41.878113
#  longitude: -87.629799
#- name: Houston
#  latitude: 29.760427
#  longitude: -95.369804
#- name: Phoenix
#  latitude: 33.448376
#  longitude: -112.074036
#- name: Philadelphia
#  latitude: 39.952583
#  longitude: -75.165222
#- name: San Antonio
#  latitude: 29.424122
#  longitude: -98.493629
#- name: San Diego
#  latitude: 32.715736
#  longitude: -117.161087
#- name: Dallas
#  latitude: 32.776664
#  longitude: -96.796988
#- name: Miami
#  latitude: 25.761680
#  longitude: -80.191790


apps:
- name: app1
  location: Hadera
  metric: up{instance="app:8080", job="app"}
  prometheus: http://prometheus:9090/
#- name: app3
#  location: Jerusalem
#  metric: up{instance="localhost:9090", job="prometheus"}
#  prometheus: http://prometheus:9090/
#- name: app4
#  location: Beer Sheva
#  metric: up{instance="app:8080", job="app"}
#  prometheus: http://prometheus:9090/
#- name: app2
#  location: Hadera
#  metric: up{instance="app:8080", job="app"}
#  prometheus: http://prometheusss:9090/
#- name: app5
#  location: Natanya
#  metric: 1 - up{instance="localhost:9090", job="prometheus"}
#  prometheus: http://prometheus:9090/
#- name: app6
#  location: Beer Sheva
#  metric: up{instance="app:8080", job="app"}
#  prometheus: http://prometheus:9090/
- name: app7
  location: Yona
  metric: 1 - up{instance="localhost:9090", job="prometheus"}
  prometheus: http://prometheusad:9090/