{{- if .Values.configFile.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "site-availability.fullname" . }}
data:
  config.yaml: |
    {{ .Values.configFile.content | toYaml | nindent 4 }}
{{- end }}
