apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "site-availability.fullname" . }}
  labels:
    {{- include "site-availability.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "site-availability.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "site-availability.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:v{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.credentials.credentialsSecretName }}
            - name: CREDENTIALS_FILE
              value: /app/credentials.yaml
            {{- end }}
            {{- if .Values.configFile.enabled }}
            - name: CONFIG_FILE
              value: /app/config.yaml
            {{- end }}
          envFrom:
            {{- range .Values.extraSecretNameForEnvFrom }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          volumeMounts:
            {{- if .Values.configFile.enabled }}
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
            {{- end }}
            {{- if .Values.credentials.credentialsSecretName }}
            - name: credentials-volume
              mountPath: /app/credentials.yaml
              subPath: credentials.yaml
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.configFile.enabled }}
        - name: config-volume
          configMap:
            name: {{ include "site-availability.fullname" . }}-config
        {{- end }}
        {{- if .Values.credentials.credentialsSecretName }}
        - name: credentials-volume
          secret:
            secretName: {{ .Values.credentials.credentialsSecretName }}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
