apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "site-availability.fullname" . }}-rules
spec:
  groups:
  - name: site-availability
    rules:
    - alert: AppDown
      expr: site_availability_status == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "App down"
        description: "The app {{ "{{" }} $labels.app }} is down in location {{ "{{" }} $labels.location }}."

    - alert: AppUnavailable
      expr: site_availability_apps_unavailable > 0
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "App unavailable"
        description: "The app(s) in location {{ "{{" }} $labels.location }} are unavailable."

    - alert: NoMetricsReceived
      expr: absent(site_availability_total_apps) == 1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Site availability - No metrics received "
        description: "No site availability metrics received from the exporter in the last 5 minutes."
