# Configuration file content for server-a
configFile:
  enabled: true
  content:
    server_settings:
      port: 8080
      sync_enable: true
      host_url: http://server-a.local
      labels:
        environment: "production"
        region: "usa"
        datacenter: "main"
        team: "platform"
      local_admin:
        enabled: true
        username: "admin"
        password: "admin"
      session_timeout: "12h"

    scraping:
      interval: "10s"
      timeout: "1s"
      max_parallel: 10

    documentation:
      title: "Server A Documentation"
      url: "https://server-a.example.com/docs"

    locations:
      - name: Houston
        latitude: 29.7604
        longitude: -95.3698
      - name: New York
        latitude: 40.7128
        longitude: -74.0060
      - name: Los Angeles
        latitude: 34.0522
        longitude: -118.2437
      - name: Chicago
        latitude: 41.8781
        longitude: -87.6298

    sources:
      - name: prom1
        type: prometheus
        labels:
          service: "core-monitoring"
          tier: "backend"
          criticality: "high"
        config:
          url: http://kube-prometheus-stack-prometheus.default.svc.cluster.local:9090
          apps:
            - name: a-app1
              location: Houston
              metric: up{job="kubelet",metrics_path="/metrics"}
              labels:
                app_type: "web-service"
                importance: "critical"
                owner: "backend-team"
            - name: a-app2
              location: New York
              metric: up{job="kubelet",metrics_path="/metrics"}
              labels:
                app_type: "monitoring"
                importance: "critical"
                owner: "sre-team"
            - name: app3
              location: Los Angeles
              metric: up{job="kubelet",metrics_path="/metrics"}
              labels:
                app_type: "monitoring"
                importance: "high"
                owner: "sre-team"
            - name: a-app4
              location: Los Angeles
              metric: up{job="kubelet",metrics_path="/metrics"}
              labels:
                app_type: "web-service"
                importance: "medium"
                owner: "backend-team"
            - name: a-app5
              location: Chicago
              metric: up{endpoint="http-metrics", instance="172.18.0.2:10257", job="kube-controller-manager", namespace="kube-system", pod="kube-controller-manager-site-availability-control-plane", service="kube-prometheus-stack-kube-controller-manager"}
              labels:
                app_type: "test-service"
                importance: "low"
                owner: "qa-team"
                inverted: "true"
            - name: a-app6
              location: Los Angeles
              metric: up{instance="app:8080", job="app"}
              labels:
                app_type: "web-service"
                importance: "medium"
                owner: "frontend-team"
