{
 "title": "Site Availability / Apps Overview",
 "tags": [ "apps-overview" ],
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "filter_label_key",
    "label": "Filter Label Key",
    "query": {
     "query": "label_names(site_availability_status)"
    }
   },
   {
    "name": "filter_label_value",
    "label": "Filter Label Value",
    "query": {
     "query": "label_values(site_availability_status, $filter_label_key)"
    }
   },
   {
    "name": "SLO",
    "query": "90,99,99.9,99.99,99.999,99.9999,99.99999"
   }
  ]
 },
 "panels": [
  { "title": "Filter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Apps Availability",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg (site_availability_status{$filter_label_key=~\"$filter_label_value\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "SLO Compliance - Apps Availability",
   "type": "table",
   "gridPos": { "h": 16, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum_over_time(avg(site_availability_status{$filter_label_key=~\"$filter_label_value\"}) by (name)[$__range:1m]) / count_over_time(avg(site_availability_status{$filter_label_key=~\"$filter_label_value\"}) by (name)[$__range:1m]) * 100 / $SLO",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apps Availability",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 19, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(avg (site_availability_status{$filter_label_key=~\"$filter_label_value\"}) by (name)[$__range:1m]) / count_over_time(avg (site_availability_status{$filter_label_key=~\"$filter_label_value\"}) by (name)[$__range:1m]) * 100)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "All Apps Data ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total Apps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (site_availability_total_apps{})"
    }
   ]
  },
  {
   "title": "Apps Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (site_availability_total_apps_up{})"
    }
   ]
  },
  {
   "title": "Apps Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(site_availability_total_apps_down{})"
    }
   ]
  },
  {
   "title": "Apps Unavailable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(site_availability_total_apps_unavailable{})"
    }
   ]
  },
  {
   "title": "Apps by Location",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(site_availability_apps{}) by (location) - avg(site_availability_apps_down{}) by (location)- avg(site_availability_apps_unavailable{}) by (location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Apps Down by Location",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "avg(site_availability_apps_down{}) by (location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Apps Unavailable by Location",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "avg(site_availability_apps_unavailable{}) by (location)",
     "legendFormat": "{{location}}"
    }
   ]
  }
 ]
}