server_settings:
  port: "8080"
  session_timeout: "12h"
  local_admin:
    enabled: true
    username: "admin"

  # Role-based authorization configuration
  roles:
    # Frontend team role - can see frontend apps
    frontend:
      team: "frontend"
      env: "production"

    # Backend team role - can see backend and shared apps
    backend:
      team: "backend"
      shared: "yes"

    # DevOps role - can see all environments
    devops:
      env: "production"
      env2: "staging" # Note: This is a separate label/value pair

    # QA role - can see staging environment
    qa:
      env: "staging"

scraping:
  interval: "30s"
  timeout: "10s"
  max_parallel: 5

documentation:
  title: "Site Availability Monitor"
  url: "https://your-docs-url.com"

locations:
  - name: "US East"
    latitude: 40.7128
    longitude: -74.0060
  - name: "EU West"
    latitude: 52.5200
    longitude: 13.4050

sources:
  - name: "frontend-app-prod"
    type: "http"
    labels:
      team: "frontend"
      env: "production"
    config:
      url: "https://app.example.com/health"
      method: "GET"
      expected_status: 200

  - name: "backend-api-prod"
    type: "http"
    labels:
      team: "backend"
      env: "production"
    config:
      url: "https://api.example.com/health"
      method: "GET"
      expected_status: 200

  - name: "shared-service"
    type: "http"
    labels:
      shared: "yes"
      env: "production"
    config:
      url: "https://shared.example.com/health"
      method: "GET"
      expected_status: 200

  - name: "staging-app"
    type: "http"
    labels:
      team: "frontend"
      env: "staging"
    config:
      url: "https://staging.example.com/health"
      method: "GET"
      expected_status: 200
