server_settings:
  local_admin:
    # Option 1: Plaintext password (for development only)
    password: "passpass123"

    # Option 2: Bcrypt hashed password (recommended for production)
    # To generate a bcrypt hash, you can use online tools or:
    # echo "passpass123" | htpasswd -bnBC 12 "" | tr -d ':\n'
    # Example bcrypt hash for "passpass123":
    # password: "$2b$12$rDKx8UXp3F8P7xYV9oGzTeBN6K8aHVWHZxXzGQQJ8E1QXh8l2F9Da"
