server_settings:
  port: "8080"
  session_timeout: "12h" # Session timeout (12 hours default)
  local_admin:
    enabled: true # Enable local admin authentication
    username: "admin" # Admin username

scraping:
  interval: "30s"
  timeout: "10s"
  max_parallel: 5

documentation:
  title: "Site Availability Monitor"
  url: "https://your-docs-url.com"

locations:
  - name: "US East"
    latitude: 40.7128
    longitude: -74.0060
  - name: "EU West"
    latitude: 52.5200
    longitude: 13.4050

sources:
  - name: "example-api"
    type: "http"
    labels:
      env: "production"
      team: "platform"
    config:
      url: "https://api.example.com/health"
      method: "GET"
      expected_status: 200
