server_settings:
  port: 8080
  sync_enable: true
  labels:
    environment: "staging"
    region: "israel"
    datacenter: "backup"
    team: "platform"

scraping:
  interval: "10s"
  timeout: "1s"
  max_parallel: 10

documentation:
  title: "Server B Documentation"
  url: "https://server-b.example.com/docs"

locations:
  - name: Beer Sheva
    latitude: 31.245381
    longitude: 34.788745
  - name: Netanya
    latitude: 33.04198
    longitude: 35.51537

sources:
  - name: prom1
    type: prometheus
    labels:
      service: "staging-monitoring"
      tier: "backend"
      criticality: "medium"
    config:
      url: http://prometheus-b:9090
      apps:
        - name: app3
          location: Beer Sheva
          metric: up{instance="app:8080", job="app"}
          labels:
            app_type: "web-service"
            importance: "medium"
            owner: "backend-team"
            stage: "testing"
        - name: b-app4
          location: Netanya
          metric: up{instance="localhost:9090", job="prometheus"}
          labels:
            app_type: "monitoring"
            importance: "high"
            owner: "sre-team"
            stage: "staging"
  - name: Server A
    type: site
    labels:
      service: "remote-monitoring"
      tier: "integration"
      criticality: "low"
    config:
      url: http://server-a:8080
