server_settings:
  port: 8090
  host_url: "http://localhost:8090"
  sync_enable: false
  labels:
    environment: "staging"
    region: "usa"
    datacenter: "backup"
    team: "platform"

scraping:
  interval: "10s"
  timeout: "1s"
  max_parallel: 10

documentation:
  title: "Server B Documentation"
  url: "https://server-b.example.com/docs"

locations:
  - name: Los Angeles
    latitude: 34.0522
    longitude: -118.2437
  - name: Chicago
    latitude: 41.8781
    longitude: -87.6298

sources:
  - name: prom1
    type: prometheus
    labels:
      service: "staging-monitoring"
      tier: "backend"
      criticality: "medium"
    config:
      url: http://prometheus-b:9090
      apps:
        - name: app3
          location: Los Angeles
          metric: up{instance="app:8080", job="app"}
          labels:
            app_type: "web-service"
            importance: "medium"
            owner: "backend-team"
            stage: "testing"
        - name: b-app4
          location: Chicago
          metric: up{instance="localhost:9090", job="prometheus"}
          labels:
            app_type: "monitoring"
            importance: "high"
            owner: "sre-team"
            stage: "staging"
  - name: Server A
    type: site
    labels:
      service: "remote-monitoring"
      tier: "integration"
      criticality: "low"
    config:
      url: http://server-a:8080
