server_settings:
  port: 8080
  sync_enable: true

scraping:
  interval: "10s"
  timeout: "1s"
  max_parallel: 10

documentation:
  title: "Server B Documentation"
  url: "https://server-b.example.com/docs"

locations:
  - name: Beer Sheva
    latitude: 31.245381
    longitude: 34.788745
  - name: Netanya
    latitude: 33.04198
    longitude: 35.51537

sources:
  - name: prom1
    type: prometheus
    url: http://prometheus-b:9090
    apps:
      - name: app3
        location: Beer Sheva
        metric: up{instance="app:8080", job="app"}
      - name: b-app4
        location: Netanya
        metric: up{instance="localhost:9090", job="prometheus"}
  - name: Server A
    type: site
    url: http://server-a:8080
