server_settings:
  oidc:
    config:
      # OIDC Client Secret (keep this secure!)
      clientSecret: your-oidc-client-secret-here

  # Optional: Keep local admin as fallback
  local_admin:
    password: your-secure-admin-password
