server_settings:
  port: "8080"
  session_timeout: 12h

  # Define roles and their label permissions
  roles:
    frontend:
      team: frontend
      env: production
    backend:
      team: backend
      env: production
    devops:
      team: devops
    qa:
      env: staging
    qa-test:
      env: testing
    eu-west:
      region: eu-west
    eu-central:
      region: eu-central

  # OIDC Configuration
  oidc:
    enabled: true
    config:
      name: Keycloak
      issuer: https://keycloak.example.com/realms/master
      clientID: site-availability
      groupScope: groups
      userNameScope: preferred_username
    permissions:
      users:
        # Individual user permissions
        john.doe:
          - frontend
          - backend
        jane.admin:
          - admin # Admin role gives full access
        bob.qa:
          - qa
          - qa-test
      groups:
        # Group-based permissions
        frontend-team:
          - frontend
        backend-team:
          - backend
        devops-team:
          - devops
          - admin # Devops group gets admin access
        qa-team:
          - qa
          - qa-test
        eu-team:
          - eu-west
          - eu-central

# Example sources with labels that match the roles
locations:
  - name: "EU West"
    latitude: 51.5074
    longitude: -0.1278

sources:
  - name: frontend-app-prod
    url: https://frontend.example.com/health
    labels:
      team: frontend
      env: production
      region: eu-west

  - name: backend-api-prod
    url: https://api.example.com/health
    labels:
      team: backend
      env: production

  - name: devops-tools
    url: https://jenkins.example.com/health
    labels:
      team: devops

  - name: staging-app
    url: https://staging.example.com/health
    labels:
      env: staging
