server_settings:
  port: 8080
  sync_enable: false
  host_url: http://localhost:8080
  labels:
    environment: "development"
    region: "local"
    datacenter: "dev"
    team: "development"
  local_admin:
    enabled: true # Enable local admin authentication
    username: "admin" # Admin username
    password: "admin" # Admin password
  session_timeout: "12h" # Session timeout (12 hours default)
  metrics_auth:
    enabled: true
    type: "basic" # or "bearer"
    username: "prometheus"
    password: "prometheus-secret"
scraping:
  interval: "10s"
  timeout: "1s"
  max_parallel: 10

documentation:
  title: "Site A Documentation"
  url: "https://site-a.example.com/docs"

locations:
  - name: Houston
    latitude: 29.7604
    longitude: -95.3698
  - name: New York
    latitude: 40.7128
    longitude: -74.0060
  - name: Los Angeles
    latitude: 34.0522
    longitude: -118.2437
  - name: Chicago
    latitude: 41.8781
    longitude: -87.6298

sources:
  - name: prom1
    type: prometheus
    labels:
      service: "dev-monitoring"
      tier: "backend"
      criticality: "low"
    config:
      url: http://prometheus:9090
      apps:
        - name: app1
          location: Houston
          metric: up{instance="app:8080", job="app"}
          labels:
            app_type: "web-service"
            importance: "low"
            owner: "dev-team"
            version: "v1.0"
        - name: app3
          location: New York
          metric: up{instance="localhost:9090", job="prometheus"}
          labels:
            app_type: "monitoring"
            importance: "medium"
            owner: "sre-team"
            version: "v2.1"
        - name: app4
          location: Los Angeles
          metric: up{instance="app:8080", job="app"}
          labels:
            app_type: "web-service"
            importance: "low"
            owner: "frontend-team"
            experimental: "true"
        - name: app5
          location: Chicago
          metric: 1 - up{instance="localhost:9090", job="prometheus"}
          labels:
            app_type: "test-service"
            importance: "low"
            owner: "qa-team"
            inverted: "true"
            experimental: "true"
        - name: app6
          location: Los Angeles
          metric: up{instance="app:8080", job="app"}
          labels:
            app_type: "web-service"
            importance: "medium"
            owner: "backend-team"
            version: "v1.2"
  - name: prom2
    type: prometheus
    labels:
      service: "secondary-monitoring"
      tier: "testing"
      criticality: "low"
    config:
      url: http://prometheus2:9090
      apps:
        - name: app2
          location: Houston
          metric: up{instance="app:8080", job="app"}
          labels:
            app_type: "web-service"
            importance: "low"
            owner: "dev-team"
            beta: "true"
        - name: app7
          location: Houston
          metric: 1 - up{instance="localhost:9090", job="prometheus"}
          labels:
            app_type: "test-service"
            importance: "low"
            owner: "qa-team"
            inverted: "true"
            beta: "true"
  - name: basic-http
    type: http
    labels:
      service: "web-monitoring"
      app: google
    config:
      apps:
        - name: google
          location: Chicago
          url: "https://www.google.com"
          ssl_verify: false
        - name: moogle
          location: Los Angeles
          url: "https://www.mooglezczcsdvdv.com"
