sources:
  - name: prom1
    config:
      auth: bearer
      token: "test-token-123"
  - name: prom2
    config:
      auth: basic
      token: "admin:prometheus"
  - name: basic-http
    config:
      apps:
        - name: prom1
          auth:
            type: "basic"
            username: "admin"
            password: "prometheus"
        - name: prom2
          auth:
            type: "bearer"
            token: "test-token-123"
