server_settings:
  port: 8080
  sync_enable: false

scraping:
  interval: "10s"
  timeout: "1s"
  max_parallel: 10

documentation:
  title: "Site A Documentation"
  url: "https://site-a.example.com/docs"

locations:
  - name: Houston
    latitude: 29.7604
    longitude: -95.3698
  - name: New York
    latitude: 40.7128
    longitude: -74.0060
  - name: Los Angeles
    latitude: 34.0522
    longitude: -118.2437
  - name: Chicago
    latitude: 41.8781
    longitude: -87.6298

sources:
  - name: prom1
    type: prometheus
    config:
      url: http://nginx:9090
      apps:
        - name: app1
          location: Houston
          metric: up{instance="app:8080", job="app"}
        - name: app3
          location: New York
          metric: up{instance="localhost:9090", job="prometheus"}
        - name: app4
          location: Los Angeles
          metric: up{instance="app:8080", job="app"}
        - name: app5
          location: Chicago
          metric: 1 - up{instance="localhost:9090", job="prometheus"}
        - name: app6
          location: Los Angeles
          metric: up{instance="app:8080", job="app"}
  - name: prom2
    type: prometheus
    config:
      url: http://nginx:9090
      apps:
        - name: app2
          location: Houston
          metric: up{instance="app:8080", job="app"}
        - name: app7
          location: Houston
          metric: 1 - up{instance="localhost:9090", job="prometheus"}
  - name: basic-http
    type: http
    labels:
      service: "web-monitoring"
      app: google
    config:
      apps:
        - name: prom1
          location: Chicago
          url: "http://nginx:9090"
        - name: prom2
          location: Los Angeles
          url: "http://nginx:9090"
