title: Site Availability Monitor
description: A comprehensive site availability monitoring solution with real-time dashboard and alerting
url: ""
baseurl: ""

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

header_pages:
  - getting-started.md
  - installation.md
  - configuration.md
  - api.md
  - frontend.md
  - deployment.md
  - development.md
  - troubleshooting.md
  - contributing.md

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Custom configuration for our dark theme
sass:
  style: compressed

# Collections for better organization
collections:
  docs:
    output: true
    permalink: /:collection/:name/
