title: Site Availability Monitor
description: A comprehensive site availability monitoring solution with real-time dashboard and alerting
url: ""
baseurl: ""

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

header_pages:
  - getting-started.md
  - installation.md
  - configuration.md
  - api.md
  - frontend.md
  - deployment.md
  - development.md
  - troubleshooting.md
  - contributing.md

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
<<<<<<< HEAD
  - README.md
=======
>>>>>>> 822a294e694b48ddcb2ddbf2a8b7e72de4f93b92

# Custom configuration for our dark theme
sass:
  style: compressed

<<<<<<< HEAD
# GitHub Pages specific settings
repository: tal/site-availability
github:
  private: false
=======
# Collections for better organization
collections:
  docs:
    output: true
    permalink: /:collection/:name/
>>>>>>> 822a294e694b48ddcb2ddbf2a8b7e72de4f93b92
