services:
  server-a:
    build:
      context: ../../..
      dockerfile: Dockerfile
    image: levytal/site-availability
    environment:
      - CONFIG_FILE=/app/config.yaml
      - CREDENTIALS_FILE=/app/credentials.yaml
    volumes:
      - ../../config/config-a.yaml:/app/config.yaml
      - ../../config/credentials-a.yaml:/app/credentials.yaml
    ports:
      - "8080:8080"
    depends_on:
      - prometheus-a
    networks:
      - site-net

  server-b:
    build:
      context: ../../..
      dockerfile: Dockerfile
    image: levytal/site-availability
    environment:
      - CONFIG_FILE=/app/config.yaml
      - CREDENTIALS_FILE=/app/credentials.yaml
    volumes:
      - ../../config/config-b.yaml:/app/config.yaml
      - ../../config/credentials-b.yaml:/app/credentials.yaml
    ports:
      - "8081:8080"
    depends_on:
      - prometheus-b
      - server-a
    networks:
      - site-net

  prometheus-a:
    image: prom/prometheus:latest
    container_name: prometheus-a
    volumes:
      - ../../prometheus/prometheus-a.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090:9090"
    networks:
      - site-net

  prometheus-b:
    image: prom/prometheus:latest
    container_name: prometheus-b
    volumes:
      - ../../prometheus/prometheus-b.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9091:9090"
    networks:
      - site-net

networks:
  site-net:
    driver: bridge
