#name: Helm Workflow
#
#on:
#  push:
#    paths:
#      - 'chart/**'
#  push:
#    tags:
#      - 'v*'
#
#jobs:
#  helm:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Run Helm lint
#        run: helm lint chart/
#
#      - name: Update image tag in values.yaml (only for tags)
#        if: startsWith(github.ref, 'refs/tags/')
#        run: |
#          TAG=${{ github.ref_name }}
#          yq eval ".image.tag = \"$TAG\"" -i chart/values.yaml
#
#      - name: Package Helm chart (only for tags)
#        if: startsWith(github.ref, 'refs/tags/')
#        run: helm package chart/ --destination release/
#
#      - name: Log in to GHCR
#        if: startsWith(github.ref, 'refs/tags/')
#        uses: docker/login-action@v2
#        with:
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Push Helm chart to GHCR (only for tags)
#        if: startsWith(github.ref, 'refs/tags/')
#        run: |
#          helm push release/*.tgz oci://ghcr.io/<your-org-or-username>
