name: Run tests and upload coverage

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_call:
    inputs:
      working-directory:
        description: "Directory to run tests in"
        required: false
        default: "./backend"
        type: string

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: go mod download

      - name: Run tests
        working-directory: ${{ inputs.working-directory }}
        run: go test -v -coverprofile=coverage.txt ./...

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ inputs.working-directory }}/coverage.txt
          fail_ci_if_error: true
