#name: Test Workflow
#
#on:
#  push:
#    paths:
#      - 'frontend/**'
#      - 'backend/**'
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    services:
#      prometheus:
#        image: prom/prometheus:latest
#        ports:
#          - 9090:9090
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Backend tests
#        run: |
#          cd backend
#          go test ./...
#          go vet ./...
#
#      - name: Frontend tests
#        run: |
#          cd frontend
#          npm ci
#          npm test
#          npx eslint .
